### ISSUE TITLE
How to change Manis Nothing sweeter than this?

### ISSUE THREAD

**Issue by ugartelon** [yursan9/manis-hugo-theme#1]
Hi, 

Thanks for sharing this fantastic blog.
I have been updating it but unable to change the part that says:

Manis
Nothing sweeter than this

I would like to put instad:
Pablo Ugarte
Telling stories from web data

How and where could I make these changes?

My email is ugartelon@gmail.com
My GitHub is https://github.com/ugartelon
Thanks

**Comment by ugartelon** [comment]
In public index html is the solution...Closed question

**Comment by yursan9** [comment]
Well, if you think you already solved the problem that's good. But, for other people who stumble upon this issue...you shouldn't change the generated HTML in public directory.

If you wan't to change the main title and subtitle, look at the file `exampleSite/config.toml`. Edit the `title` and `params.tagline` paramater in the config file.

```toml
title = "Pablo Ugarte"
...
[params]
    tagline = "Telling stories from web data"
```
