### ISSUE TITLE
 icon-social size

### ISSUE THREAD

**Issue by whufanwei** [yursan9/manis-hugo-theme#12]
Hi,

Thanks for sharing this fantastic blog.
I want to change the icon-social size，from 3rem to 2rem，like this:

`.icon-social {
  width: 2rem;
  height: 2rem;
}
`
so it works at homepage, but in the single post page,  icon-social size remains 3rem.

I don't know how to change it.

**Comment by yursan9** [comment]
Did you tried using customCSS option?

**Comment by yursan9** [comment]
Wait, I guess you didn't know this theme have custom CSS option. You can open your site `config.toml` and on `params` add this line into it:

```
[params]
    customCSS = ["/css/icon.css"]
```

Then, make new file on `static/css/icon.css`, and write your custom CSS into it:
```
.icon-social {
    width: 2rem;
    height: 2rem;
} 
```

Viola, it should override the default icon's size.

**Comment by whufanwei** [comment]
oh, I find the reason.

I make new file "custom.css" in static folder, and I use this:

`	# If false, use minified CSS (ui.min.css)
	debugCSS = false

	# Custom CSS
	customCSS = ['custom.css']
`
so it does work in homepage , bu not in other pages.

I change the "debugCSS = true",so it works. 

thank you.

**Comment by yursan9** [comment]
It should works even without the `debugCSS` option. Actually, the `debugCSS` option is gone on newer version of the theme.
