### ISSUE TITLE
long preformated on mobile

### ISSUE THREAD

**Issue by akhenakh** [yursan9/manis-hugo-theme#13]
Hi love your theme !

As you can see a long preformated text looks bogus on Safari mobile:

![IMG_2A8389110ADF-1](https://user-images.githubusercontent.com/218430/64869824-216b1f00-d610-11e9-9b57-6835d45e8e70.jpeg)

Post visible at https://blog.nobugware.com/post/2019/using-github-actions-with-golangci-linter/

Thanks

**Comment by yursan9** [comment]
I just need to add `overflow-wrap: break-word` on `pre>code`. I don't have phone with such a small width, sorry for the oversight.
