### ISSUE TITLE
Not able to publish a new post

### ISSUE THREAD

**Issue by ugartelon** [yursan9/manis-hugo-theme#2]
Thanks for the reply the other day. Now sorted.

Having problems publishing live posts.

I am getting the below message in console:

Execution halted
Error in render_page(f) : 
  Failed to render '2017-09-14-electric-car-revolution-and-evolution-of-metal-prices.Rmd'
Calls: <Anonymous> ... <Anonymous> -> build_site -> build_rmds -> in_dir -> render_page
In addition: Warning messages:
1: In file.rename(from, to) :
  cannot rename file '2017-09-13-json-and-lon-lat_files/htmlwidgets' to '/Users/ugartelon/Documents/R Working Directory/Blog/First/static/rmarkdown-libs/htmlwidgets', reason 'Directory not empty'
2: In file.rename(from, to) :
  cannot rename file '2017-09-13-json-and-lon-lat_files/jquery' to '/Users/ugartelon/Documents/R Working Directory/Blog/First/static/rmarkdown-libs/jquery', reason 'Directory not empty'
3: In file.rename(from, to) :
  cannot rename file '2017-09-13-json-and-lon-lat_files/leaflet' to '/Users/ugartelon/Documents/R Working Directory/Blog/First/static/rmarkdown-libs/leaflet', reason 'Directory not empty'
4: In file.rename(from, to) :
  cannot rename file '2017-09-13-json-and-lon-lat_files/leafletfix' to '/Users/ugartelon/Documents/R Working Directory/Blog/First/static/rmarkdown-libs/leafletfix', reason 'Directory not empty'
5: In file.rename(from, to) :
  cannot rename file '2017-09-13-json-and-lon-lat_files/leaflet-label' to '/Users/ugartelon/Documents/R Working Directory/Blog/First/static/rmarkdown-libs/leaflet-label', reason 'Directory not empty'
6: In file.rename(from, to) :
  cannot rename file '2017-09-13-json-and-lon-lat_files/Proj4Leaflet' to '/Users/ugartelon/Documents/R Working Directory/Blog/First/static/rmarkdown-libs/Proj4Leaflet', reason 'Directory not empty'
7: In file.rename(from, to) :
  cannot rename file '2017-09-13-json-and-lon-lat_files/leaflet-binding' to '/Users/ugartelon/Documents/R Working Directory/Blog/First/static/rmarkdown-libs/leaflet-binding', reason 'Directory not empty'
[1] TRUE
Execution halted

Exited with status 1.

**Comment by yursan9** [comment]
Can you tell me what are you trying to do?
It's look like the target directory is not empty.

**Comment by ugartelon** [comment]
I have to say that despite getting the message error I am somehow able to publish the posts (closing RStudio and reopening and trying different things many times).

But sure there is a simpler, error free way.

This error occurs when I type in console build_site() whenever I want to publish a new post.

**Comment by yursan9** [comment]
From what I can gather from your comment, you're using RStudio to write and publish your markdown, right? Can you at least try using different theme? If the error persist, then it was probably RStudio specific problem.

I can't help you much if you're using RStudio (and Windows too), because I don't use the two applications.

**Comment by ugartelon** [comment]
Ok! Thank for the response

Yes, I am using R Studio.

Good news is that despite these messages I am able to post things.

One question if I may. 

How could I justify a list or header text for example:


#### MASTER IN DATA ANALYTICS ISDI, MADRID (Octubre 2016 – Agosto 2017)

So…I have MASTER IN DATA ANALYTICS ISDI, MADRID left aligned and  (Octubre 2016 – Agosto 2017) right aligned in md.


MASTER IN DATA ANALYTICS ISDI, MADRID                                                                            (Octubre 2016 – Agosto 2017)


Thanks

**Comment by yursan9** [comment]
Currently, you can't do that, and it's outside the scope of this theme. But...because of the beauty of open source, you can fork and edit this theme with your changes.

Or you can use raw HTML in Markdown and use CSS to right aligned the text.
