### ISSUE TITLE
Enhancement: Add Norwegian Nynorsk translation

### ISSUE THREAD

**Issue by aujawindar** [yursan9/manis-hugo-theme#26]
The following can be put in `i18n/nn.toml` to add translation to Nynorsk:

[latestPost]
other = "Nye innlegg"

[latestWork]
other = "Nye verk"

[license]
other = "Vilkår"

[toUp]
other = "Til toppen"

[workHomepage]
other = "Heim"

[usedTheme]
other = "Bunad:"

[seeAlso]
other = "Sjå òg"

**Comment by yursan9** [comment]
Make PR please
