### ISSUE TITLE
Misaligned next and previous post links 

### ISSUE THREAD

**Issue by 0x1CC** [yursan9/manis-hugo-theme#3]
Hi,

At the end of each post there are links to the previous and next post. Currently those anchor tags have a display of "block", so when both of them are present, they look misaligned.

![20180319-165724](https://user-images.githubusercontent.com/37168838/37620669-a60b2ed8-2b9b-11e8-8769-f781d5ffb372.png)

Adding `display: flex` and `justify-content: space-between` to the parent container of .prev-post and .next-post fixes the issue. https://github.com/0x1CC/manis-hugo-theme/commit/1b718487b09d2ce5eac98070b71f0296c7acb56c

And finally, thank you for the good theme, it looks nice and including the non minified CSS helps a lot.

Cristian

**Comment by yursan9** [comment]
Thank you for your kind words!

And regarding the issue of misaligned links for post navigation. It's deliberated decision. I don't want to introduce CSS Grid, or flexbox in this theme to make everything simple and accesible from variety of devices or browser.

**Comment by yursan9** [comment]
Oh, and happy hacking! I like to see other people using and modifying my theme!
