### ISSUE TITLE
Fix the path of config.toml

### ISSUE THREAD

**Issue by Fziliotti** [yursan9/manis-hugo-theme#9]
Hi Yursan9,

On the section 'get started' of your readme, the correct path of config.toml is 'themes/manis/exampleSite/config.toml config.toml', with a 's' on the final of 'theme'.  😃

**Comment by yursan9** [comment]
Thank you @Fziliotti. It's been fixed by ef5eff8e34f31e7a9576b3f587dea8ab5dcc0ca2
